apiVersion: apps/v1

kind: Deployment
metadata:
  name: 'nodeserver'
  labels:
    app: 'nodeserver'

spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 2
  template:
    metadata:
      name: 'nodeserver'
      labels:
        app: 'nodeserver'
    spec:
      serviceAccount: serviceaccount-server # Equals to ServiceAccount -> name
      containers:
        - name: nodeserver
          image: 'henriqueholtz/nodeserver:latest'

          resources: # This seize/reserve this resources
            requests:
              # 1vCPU: 1000m (milicores)
              cpu: 200m # or 0.5 (at porcentage)
              memory: 155Mi
            limits:
              cpu: 1000m
              memory: 200Mi

          # startupProbe: # HTTPS, COMMAND or TCP
          #   httpGet:
          #     path: '/healthz'
          #     port: 3000 # Service port (don't container port)
          #   periodSeconds: 10
          #   failureThreshold: 30
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   initialDelaySeconds: 10

          # livenessProbe: # HTTPS, COMMAND or TCP
          #   httpGet:
          #     path: '/healthz'
          #     port: 3000 # Service port (don't container port)
          #   periodSeconds: 10
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   # initialDelaySeconds: 10 # Needs when don't using startupProbe

          # readinessProbe:
          #   httpGet:
          #     path: '/healthz'
          #     port: 3000 # Service port (don't container port)
          #   periodSeconds: 10
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   # initialDelaySeconds: 10 # Needs when don't using startupProbe

          envFrom:
            - configMapRef:
                name: nodeserver-env
            - secretRef:
                name: nodeserver-secret
          volumeMounts:
            - mountPath: '/appdevbuild/files' # path where app is running (container for example)
              name: configmapvol # Equals to volume name below
            - mountPath: '/appdevbuild/pvc'
              name: nodeserver-pvc-vol

          #envFrom to select all from configMap
          #env to select individual keys
          # env:
          #   - name: name
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: NAME
          #   - name: age
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: AGE

      volumes:
        - name: nodeserver-pvc-vol
          persistentVolumeClaim:
            claimName: nodeserver-pvc
        - name: configmapvol
          configMap:
            name: configmap-file
            items:
              - key: text
                path: 'readfile.txt'
